# Generated by Django 4.2.4 on 2023-08-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='numberReviews',
            new_name='reviewCount',
        ),
        migrations.AddField(
            model_name='product',
            name='imageAlt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
