# Generated by Django 4.2.4 on 2023-08-12 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='imageSrc',
        ),
    ]
