products = [
    {
        "_id": "1",
        "name": "Organize Basic Set (Walnut)",
        "version": {"name": "1.0", "date": "June 5, 2021", "datetime": "2021-06-05"},
        "price": "$149",
        "rating": 5,
        "reviewCount": 38,
        "imageSrc": "/assets/images/airpods.jpg",
        "imageAlt": "TODO",
        "href": "/product/1",
        "description": "The Application UI Icon Pack comes with over 200 icons in 3 styles: outline, filled, and branded. This playful icon pack is tailored for complex application user interfaces with a friendly and legible look.",
        "highlights": [
            "200+ SVG icons in 3 unique styles",
            "Compatible with Figma, Sketch, and Adobe XD",
            "Drawn on 24 x 24 pixel grid",
        ],
    },
    {
        "_id": "2",
        "name": "Organize Pen Holder",
        "version": {"name": "1.0", "date": "June 5, 2021", "datetime": "2021-06-05"},
        "price": "$15",
        "rating": 5,
        "reviewCount": 18,
        "imageSrc": "/assets/images/kimi.jpg",
        "imageAlt": "TODO",
        "href": "/product/2",
        "description": "The Application UI Icon Pack comes with over 200 icons in 3 styles: outline, filled, and branded. This playful icon pack is tailored for complex application user interfaces with a friendly and legible look.",
        "highlights": [
            "200+ SVG icons in 3 unique styles",
            "Compatible with Figma, Sketch, and Adobe XD",
            "Drawn on 24 x 24 pixel grid",
        ],
    },
    {
        "_id": "3",
        "name": "Organize Sticky Note Holder",
        "version": {"name": "1.0", "date": "June 5, 2021", "datetime": "2021-06-05"},
        "price": "$15",
        "rating": 5,
        "reviewCount": 14,
        "imageSrc": "/assets/images/phone.jpg",
        "imageAlt": "TODO",
        "href": "/product/3",
        "description": "The Application UI Icon Pack comes with over 200 icons in 3 styles: outline, filled, and branded. This playful icon pack is tailored for complex application user interfaces with a friendly and legible look.",
        "highlights": [
            "200+ SVG icons in 3 unique styles",
            "Compatible with Figma, Sketch, and Adobe XD",
            "Drawn on 24 x 24 pixel grid",
        ],
    },
    {
        "_id": "4",
        "name": "tshirt",
        "version": {"name": "1.0", "date": "June 5, 2021", "datetime": "2021-06-05"},
        "price": "$10",
        "rating": 2,
        "reviewCount": 5,
        "imageSrc": "/assets/images/tshirt.jpg",
        "imageAlt": "TODO",
        "href": "/product/4",
        "description": "The Application UI Icon Pack comes with over 200 icons in 3 styles: outline, filled, and branded. This playful icon pack is tailored for complex application user interfaces with a friendly and legible look.",
        "highlights": [
            "200+ SVG icons in 3 unique styles",
            "Compatible with Figma, Sketch, and Adobe XD",
            "Drawn on 24 x 24 pixel grid",
        ],
    },
    {
        "_id": "5",
        "name": "tshirt",
        "version": {"name": "1.0", "date": "June 5, 2021", "datetime": "2021-06-05"},
        "price": "$10",
        "rating": 2,
        "reviewCount": 5,
        "imageSrc": "/assets/images/tshirt.jpg",
        "imageAlt": "TODO",
        "href": "/product/5",
        "description": "The Application UI Icon Pack comes with over 200 icons in 3 styles: outline, filled, and branded. This playful icon pack is tailored for complex application user interfaces with a friendly and legible look.",
        "highlights": [
            "200+ SVG icons in 3 unique styles",
            "Compatible with Figma, Sketch, and Adobe XD",
            "Drawn on 24 x 24 pixel grid",
        ],
    },
    {
        "_id": "6",
        "name": "tshirt",
        "version": {"name": "1.0", "date": "June 5, 2021", "datetime": "2021-06-05"},
        "price": "$10",
        "rating": 2,
        "reviewCount": 5,
        "imageSrc": "/assets/images/2.jpg",
        "imageAlt": "TODO",
        "href": "/product/6",
        "description": "The Application UI Icon Pack comes with over 200 icons in 3 styles: outline, filled, and branded. This playful icon pack is tailored for complex application user interfaces with a friendly and legible look.",
        "highlights": [
            "200+ SVG icons in 3 unique styles",
            "Compatible with Figma, Sketch, and Adobe XD",
            "Drawn on 24 x 24 pixel grid",
        ],
    },
    {
        "_id": "7",
        "name": "tshirt",
        "version": {"name": "1.0", "date": "June 5, 2021", "datetime": "2021-06-05"},
        "price": "$10",
        "version": {"name": "1.0", "date": "June 5, 2021", "datetime": "2021-06-05"},
        "rating": 2,
        "reviewCount": 5,
        "imageSrc": "/assets/images/3.jpg",
        "imageAlt": "TODO",
        "href": "/product/7",
        "description": "The Application UI Icon Pack comes with over 200 icons in 3 styles: outline, filled, and branded. This playful icon pack is tailored for complex application user interfaces with a friendly and legible look.",
        "highlights": [
            "200+ SVG icons in 3 unique styles",
            "Compatible with Figma, Sketch, and Adobe XD",
            "Drawn on 24 x 24 pixel grid",
        ],
    },
]
